// Short original wellbeing guidance. No external content, media or medical claims.
export const RESOURCE_CATEGORIES = ['Academic Stress', 'Exam Anxiety', 'Sleep', 'Focus', 'Procrastination', 'Social Anxiety', 'Mindfulness', 'Grounding', 'Burnout', 'Time Management', 'Homesickness', 'Self-Confidence'] as const;
export const STARTER_RESOURCES = [
  { id: 'starter-stress-reset', title: 'A gentle stress reset', description: 'Make a little space when your day feels busy.', category: 'Academic Stress', featured: true, duration: '2 min', type: 'Practice', active: true, summary: 'Pause and let your shoulders relax. Take a few comfortable breaths without forcing them. Choose one small task you can do next, and leave the rest for later.' },
  { id: 'starter-sleep-wind-down', title: 'Wind down for sleep', description: 'Create a calmer transition from study to rest.', category: 'Sleep', featured: true, duration: '5 min', type: 'Guide', active: true, summary: 'Put study materials aside and lower distractions when you can. Write down one task for tomorrow so you can stop rehearsing it tonight. Choose a quiet activity that helps you settle.' },
  { id: 'starter-focus-one-step', title: 'Focus on one small step', description: 'Find a manageable starting point.', category: 'Focus', duration: '3 min', type: 'Practice', active: true, summary: 'Pick one task and break it into a tiny first step. Set aside a short period to try that step. When you finish, pause and decide whether to continue or take a break.' },
  { id: 'starter-anxiety-grounding', title: 'Notice your surroundings', description: 'A simple pause to reconnect with the present.', category: 'Grounding', featured: true, duration: '2 min', type: 'Practice', active: true, summary: 'If comfortable, notice a few things you can see, hear and feel around you. Rest your feet on the floor and let your breathing find its own rhythm. You can stop this practice at any time.' },
  { id: 'starter-mindfulness-walk', title: 'A mindful moment outdoors', description: 'Notice the world at your own pace.', category: 'Mindfulness', duration: '5 min', type: 'Practice', active: true, summary: 'Choose a safe, comfortable place to sit or walk. Notice the light, sounds and movement nearby. There is no need to clear your mind; gently return attention to what you notice.' },
  { id: 'starter-academic-pressure', title: 'Make room around exam pressure', description: 'Balance your study plan with moments of care.', category: 'Exam Anxiety', duration: '4 min', type: 'Guide', active: true, summary: 'List the topics you need to cover and choose one realistic priority for today. Include breaks and meals in your plan. If the workload feels too much, consider contacting a tutor, campus support or someone you trust.' },
  { id: 'starter-procrastination-start', title: 'Start without doing it all', description: 'Try a tiny first step when starting feels difficult.', category: 'Procrastination', duration: '2 min', type: 'Practice', active: true, summary: 'Open the task and choose a step small enough to try now. You might write a heading or read one paragraph. Notice the effort of starting, then decide what feels manageable next.' },
  { id: 'starter-social-connection', title: 'A low-pressure connection', description: 'Choose a comfortable way to connect with others.', category: 'Social Anxiety', duration: '3 min', type: 'Practice', active: true, summary: 'Consider a small interaction that feels manageable, such as greeting someone familiar or sending a friendly message. You can take your time and choose your own pace. Reach out to trusted support if social worries are interfering with daily life.' },
  { id: 'starter-burnout-pause', title: 'Make space for a pause', description: 'Notice your energy before adding another task.', category: 'Burnout', duration: '3 min', type: 'Practice', active: true, summary: 'Pause to notice whether you need rest, food or support. Pick one demand you can postpone or discuss with someone. If exhaustion persists, consider talking with campus support about your workload.' },
  { id: 'starter-time-plan', title: 'A kinder plan for today', description: 'Plan a realistic day with room for breaks.', category: 'Time Management', duration: '4 min', type: 'Practice', active: true, summary: 'Choose up to three priorities for today. Estimate the time each might take and leave space between tasks. Include meals and breaks. Adjust the plan when circumstances change rather than treating it as a test.' },
  { id: 'starter-homesickness-connection', title: 'Carry a little home with you', description: 'Find small comforts while settling into campus life.', category: 'Homesickness', duration: '4 min', type: 'Practice', active: true, summary: 'Choose a familiar comfort, such as music, a meal or a conversation with someone from home. Consider one small campus routine that could help you feel more settled. Give yourself time to adjust and seek campus support when you need it.' },
  { id: 'starter-confidence-effort', title: 'Notice your own effort', description: 'Recognize progress that is easy to overlook.', category: 'Self-Confidence', duration: '3 min', type: 'Practice', active: true, summary: 'Name one small thing you handled today, even if it was difficult. Consider what helped you try. You can recognize effort without comparing yourself with others or needing to get everything right.' },
] as const;
